#!/usr/bin/env bash
# The whole deployment on this machine, in one command:
#
#   ops/run-local.sh                # bring it up
#   ops/run-local.sh --rebuild-web  # …and re-export the web bundle first
#   ops/run-local.sh --down         # stop it, keep the data
#
# It is the production compose stack (`ops/docker-compose.prod.yml`) with the
# local overlay: the real service image, a real Postgres, the production Caddy
# with the production Caddyfile, the exported web app in front of it, and a
# real OpenRouter key. Backups, metrics and TLS are the only things left out;
# `ops/DEPLOY.md` §0 says what that costs.
#
# The model key is the one value this cannot invent. Put `OPENROUTER_API_KEY`
# in the repo-root `.env` (where the trial suite already reads it from) or in
# the environment. Everything else is generated into `ops/.env.local`.
set -euo pipefail
cd "$(dirname "$0")/.."

ENV_FILE=ops/.env.local
WEB_URL=http://127.0.0.1:58080
API_URL=http://127.0.0.1:58090

compose() {
	docker compose --env-file "$ENV_FILE" \
		-f ops/docker-compose.prod.yml -f ops/docker-compose.local.yml "$@"
}

if [ -z "${OPENROUTER_API_KEY:-}" ] && [ -f .env ]; then
	# Read, never source: `.env` is a values file, not a script to execute.
	OPENROUTER_API_KEY=$(sed -n 's/^OPENROUTER_API_KEY=//p' .env | tail -1)
fi
: "${OPENROUTER_API_KEY:?put OPENROUTER_API_KEY in .env or the environment}"

# Generated every run, so a rotated key lands without anyone remembering to
# copy it. The S3 and age values are placeholders: the backup sidecar is off in
# the local overlay, but compose still interpolates the whole file, so the
# `${NAME:?}` guards that protect a real deploy have to be satisfied here too.
# ponytail: a fixed Postgres password — the volume keeps whatever it was
# created with, so a generated one would break on the second run, and nothing
# but the compose network can reach this database anyway.
cat > "$ENV_FILE" <<ENV
# Generated by ops/run-local.sh. Edits are overwritten on the next run.
SITE_ADDRESS=:8080
ACME_EMAIL=local@example.invalid
WEB_APP_URL=$WEB_URL
POSTGRES_PASSWORD=cashkit
OPENROUTER_API_KEY=$OPENROUTER_API_KEY
SENTRY_DSN=
MAIL_PROVIDER_API_KEY=
S3_ENDPOINT=unused-locally
S3_BUCKET=unused-locally
S3_ACCESS_KEY_ID=unused-locally
S3_SECRET_ACCESS_KEY=unused-locally
BACKUP_AGE_RECIPIENT=unused-locally
ENV
chmod 600 "$ENV_FILE"

if [ "${1:-}" = "--down" ]; then
	compose down
	exit 0
fi

# The bundle is gitignored and slow to build, so it is built when it is not
# there and on request, never on every start.
if [ ! -f apps/client/dist/index.html ] || [ "${1:-}" = "--rebuild-web" ]; then
	[ -d node_modules ] || npm install
	npm run export:web --workspace @cashkit/client
fi

compose up -d --build --wait

# Migrations are explicit here for the same reason they are explicit in
# production (`ops/DEPLOY.md` §4): a service that migrates as it boots gives a
# rollback nowhere to stand.
compose exec -T service python -m cashkit_service.migrate

cat <<MSG

  app     $WEB_URL
  api     $API_URL          (healthz, and what curl -N watches)

Sign in with any address. No mail provider is configured locally, so the
magic link is printed to the service log:

  docker compose --env-file $ENV_FILE \\
    -f ops/docker-compose.prod.yml -f ops/docker-compose.local.yml \\
    logs -f service | grep magic-link

Stop it with \`ops/run-local.sh --down\`; the books and the database survive.
MSG
